### ISSUE TITLE
updating specifications is the point, but you have a counter example in the document

### ISSUE THREAD

**Issue by hardaker** [intarchboard/draft-protocol-maintenance#68]
In section 5 there is

> most inteoperability problems do not require...  

This almost reads counter to the rest of the document.  The whole
  point of the document is that specifications need updating when
  interoperability concerns are found, but this paragraph says the
  opposite.  I get the point behind it, but shouldn't bugs also be
  clarified in the specifications if they derive from specification
  interpretation?

**Comment by martinthomson** [comment]
Not really.  My view is that this is an important point to make (albeit a minor one in this context).

Many interoperability problems of the sort we're concerned with arise from a flat-out bad implementation.  I've seen tons of examples over time where there is a major deployment with an unambiguous bug.  The spec was clear and correct, everyone agreed that it was a bug - including the offending entity, often - but it forced *others* to deal with it by virtue of the bug being widely deployed.

I've also had a ton of positive experiences, where the bug is just fixed.  Probably more so than the former honestly.

**Comment by DavidSchinazi** [comment]
I find myself agreeing with both of you. What do you think of #68 as a potential path forward here?
